site_name: lernOS Prozessmodellierung Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen:
      - Was ist Prozessmodellierung: 1-1-Was-ist-Prozessmodellierung.md
      - Warum ein Lernpfad Prozessmodellierung?: 1-2-Warum-ein-Lernpfad-PM.md
      - Aufbau des Lernpfads: 1-3-Aufbau-des-Lernpfads.md
      - Lernunterlagen: 1-4-Lernunterlagen.md
      - Ressourcen & Quellennachweise: 1-5-Ressourcen.md
    - Lernpfad:
      - Mach dich mit den Grundlagen vertraut (Kata): 2-1-Kata-Grundlagen.md
      - Dein erstes Diagramm (Happy-Path) (Kata): 2-2-Kata-Happy-Path.md
      - Triff deine ersten Entscheidungen (Kata): 2-3-Kata-Entscheidungen.md
      - Exkurs-Markierungen, Aufgabentypen & Daten (Kata): 2-4-Kata-Markierungen.md
      - Von Pools und Lanes (Kata): 2-5-Kata-Pools-Lanes.md
      - Unterprozesse und Nachrichtenflüsse (Kata): 2-6-Kata-Unterprozesse.md
      - Exkurs-Eventtypen (Kata): 2-7-Kata-Eventtypen.md
      - Decision Model and Notation(DMN)-Grundlagen (Kata): 2-8-Kata-DMN.md
      - Datentypen und HIT-Policy (Kata): 2-9-Kata-Datentypen.md
      - Dein erstes komplexes DRD (Kata): 2-10-Kata-DRD.md
      - Dein Meisterstück (Kata): 2-11-Kata-Meisterstueck.md
      - Retrospektive & Feier: 2-12-Kata-Retrospektive.md
    - Anhang: 3-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-Guide-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-Guide-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-Guide-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-Guide-de.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-prozessmodellierung/blob/master/de/lernOS-Prozessmodellierung-Guide-de.mobi
    - Links:
      - lernOS Website: https://lernos.org
      - lernOS Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-template'
repo_url: 'https://github.com/cogneon/lernos-template'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
